ui: mocha-bdd
concurrency: 1
tunnel:
  type: ngrok
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: [8, latest]
  - name: ie
    version: 10..latest
  - name: microsoftedge
    version: latest
  - name: iphone
    version: 8.4
  - name: android
    version: 4.4
