ui: mocha-bdd
browsers:
  - name: chrome
    version: 50..latest
  - name: firefox
    version: 45..latest
  - name: safari
    version: [7, 8, 9..latest]
  - name: ie
    version: 10..latest
  - name: microsoftedge
    version: 13..latest
  - name: iphone
    version: [7.0, 8.4, 9.2]
  - name: ipad
    version: [7.0, 8.4, 9.2]
  - name: android
    version: 4.4..latest
