ui: mocha-bdd
tunnel:
  type: localtunnel
  https: true
browsers:
  - name: chrome
    version: 42..latest
  - name: firefox
    version: 45..latest
  - name: safari
    version: [8, 9..latest]
  - name: ie
    version: 10..latest
  - name: microsoftedge
    version: 13..latest
  - name: iphone
    version: [8.4, 9.2]
  - name: ipad
    version: [8.4, 9.2]
  - name: android
    version: 4.4..latest
